name = "Cruise"
uuid = "d855907b-85bf-40b2-8b45-fabe493c1faa"
authors = ["Kaptue Elisee"]
version = "0.3.0"

[deps]
EventNotifiers = "de92ec2b-fb1f-40f8-8e84-3094df8dc533"
GDMathLib = "ed54f85f-91e8-4912-9e4a-a43af611f8a9"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
NodeTree = "2904b71e-4df0-4a82-a724-4bbee9184de7"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
