name = "AssetCrates"
uuid = "d8559f7b-85bf-40b2-8b45-fabe493c1faa"
authors = ["Kaptue Elisee"]
version = "0.5.0"

[deps]
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
LibSndFile = "b13ce0c6-77b0-50c6-a2db-140568b8d1a5"
SimpleDirectMediaLayer = "98e33af6-2ee5-5afd-9e75-cbc738b767c4"

[compat]
julia = "1.8"
FileIO = "1.17"
LibSndFile = "2.4"
SimpleDirectMediaLayer = "0.5"
